name: check-crlf
author: erclu
description: "Checks for non-binary files with CRLF endings in given path"

branding:
  icon: file-text
  color: gray-dark

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.path }}
    - ${{ inputs.exclude }}

inputs:
  path:
    description: Path to check
    required: false
    default: "."
  exclude:
    description: Space seperated list of dirs to exclude
    required: false
    default: ""
#
# # TODO return exact number?
# outputs:
#   files-found:
#     description: Number of files with CRLF endings
