name: Test this action

on: push

jobs:
  should-fail:
    name: Test action with wrong endings
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # Use default path
      - name: this action should fail
        uses: erclu/check-crlf@master
        # this mapping prevents job from failing when this step fails as expected
        continue-on-error: true

      # TODO how to check that previous step failed when continue-on-error is true?
  should-succeed:
    name: Test action with correct endings
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: this action should succeed
        uses: erclu/check-crlf@master
        with:
          path: ./test-files/good
