name: Test this action

on: 
  push:  
  pull_request:

jobs:
  test:
    name: Test action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: |
          sh test.sh
