name: Test this action

on: push

jobs:
  test:
    name: Test action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create test files
        run: |

      - run: |
          sh entrypoint.sh temp "ignored"
